kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jupyter-notebook
  template:
    metadata:
      labels:
        component: jupyter-notebook
    spec:
      containers:
        - name: spark-master
          image: jerryjung/pyspark-notebook:latest
          command: ["start-notebook.sh"]
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: 100m

---

kind: Service
apiVersion: v1
metadata:
  name: jupyter-notebook
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30088
  selector:
    component: jupyter-notebook

