kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jupyter-notebook
  template:
    metadata:
      labels:
        component: jupyter-notebook
    spec:
      containers:
        - name: spark-master
          image: jerryjung/scipy-notebook:latest
          command: ["start-notebook.sh"]
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: 100m

---

metadata:
  name: spark-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: jerryjung/spark-cluster:latest
          command: ["/spark-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
---

kind: Service
apiVersion: v1
metadata:
  name: jupyter-notebook
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    component: jupyter-notebook
	
---

kind: Service
apiVersion: v1
metadata:
  name: spark-master
spec:
  ports:
    - port: 7077
      targetPort: 7077
  selector:
    component: spark-master

---

kind: Service
apiVersion: v1
metadata:
  name: spark-webui
  namespace: spark-cluster
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    component: spark-master

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: jerryjung/spark-cluster:latest
          command: ["/spark-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m

